#!/usr/bin/env bash
# acascac 
awk '
{
  ip = $1

  # 3 haneli status code genellikle requestten sonra gelir
  for (i = 1; i <= NF; i++) {
    if ($(i-1) ~ /^"[^"]*$/ && $i ~ /^[0-9]{3}$/) {
      code = $i
      break
    }
  }

  if (ip ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ && code ~ /^[0-9]{3}$/)
    print ip, code
}' apache-access.log | sort | uniq -c | sort -nr | awk '{ printf "%d %s %s\n", $1, $2, $3 }'
