#!/usr/bin/env bash

for pid in /proc/[0-9]*; do
    if [ -r "$pid/comm" ]; then
        name=$(<"$pid/comm")
        if [[ "$name" == *bash* ]]; then
            echo "$(basename "$pid") $name"
        fi
    fi
done
