#!/usr/bin/env bash
# dasdads
# Find the PID of the script named 4-to_infinity_and_beyond and kill it
for pid in $(pidof -x 4-to_infinity_and_beyond); do
    if [ "$pid" != "$$" ]; then
        kill "$pid"
    fi
done
