#!/usr/bin/env bash
# shellcheck disable=SC2009
# dadasdasd
# Find PID(s) of the 7-highlander process and kill them
ps -eo pid,cmd | grep '[7]-highlander' | awk '{print $1}' | while read -r pid; do
    kill "$pid"
done
